# Generated by Django 5.1 on 2024-10-26 12:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_date_article_discount_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('about', tinymce.models.HTMLField(blank=True)),
                ('news_rule', models.BooleanField(default=False)),
                ('copy_trading', models.BooleanField(default=False)),
                ('consistency_rule', models.BooleanField(default=False)),
                ('countries_prohibited', models.TextField(blank=True)),
                ('crypto_payout_option', models.BooleanField(default=False)),
                ('daily_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('years_of_operation', models.PositiveIntegerField(blank=True, null=True)),
                ('trading_platform', models.CharField(blank=True, max_length=250)),
                ('phase_type', models.CharField(blank=True, choices=[('one_phase', 'One Phase'), ('two_phase', 'Two Phase'), ('three_phase', 'Three Phase'), ('four_phase', 'Four Phase'), ('instant_funding', 'Instant Funding')], max_length=50, null=True)),
                ('phase_description', models.TextField(blank=True, null=True)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('account_size', models.PositiveIntegerField(blank=True, null=True)),
                ('leverage', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
