# Generated by Django 5.1 on 2024-12-19 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_date_article_discount_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('firm_type', models.CharField(blank=True, max_length=100)),
                ('drawdown_type', models.CharField(blank=True, max_length=100)),
                ('payout_frequency', models.CharField(blank=True, max_length=100)),
                ('news_rule', models.BooleanField(default=False)),
                ('copy_trading', models.BooleanField(default=False)),
                ('consistency_rule', models.BooleanField(default=False)),
                ('two_percent_rule', models.BooleanField(default=False)),
                ('stop_loss_rule', models.BooleanField(default=False)),
                ('countries_prohibited', models.TextField(blank=True)),
                ('payout_options', models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Cryptocurrency', 'Cryptocurrency'), ('Skrill', 'Skrill'), ('Neteller', 'Neteller')], max_length=250))),
                ('payment_options', models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cryptocurrency', 'Cryptocurrency'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe')], max_length=250))),
                ('account_plans', models.JSONField(blank=True, default=list)),
                ('trading_platforms', models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5'), ('CTrader', 'CTrader'), ('MatchTrader', 'MatchTrader'), ('DXTrade', 'DXTrade'), ('In-House Trading Platform', 'In-House Trading Platform')], max_length=250))),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('secret', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
    ]
