# Generated by Django 5.1 on 2024-10-29 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_date_article_discount_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('about', models.TextField(blank=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('firm_type', models.CharField(blank=True, max_length=100)),
                ('news_rule', models.BooleanField(default=False)),
                ('copy_trading', models.BooleanField(default=False)),
                ('consistency_rule', models.BooleanField(default=False)),
                ('two_percent_rule', models.BooleanField(default=False)),
                ('countries_prohibited', models.TextField(blank=True)),
                ('payout_options', models.CharField(blank=True, max_length=250)),
                ('payment_options', models.CharField(blank=True, max_length=250)),
                ('account_plans', models.JSONField(blank=True, default=list)),
                ('trading_platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5'), ('CTrader', 'CTrader'), ('MatchTrader', 'MatchTrader'), ('DXTrade', 'DXTrade'), ('In-House Trading Platform', 'In-House Trading Platform')], max_length=250), blank=True, default=list, size=None)),
            ],
        ),
    ]
