# Generated by Django 5.1 on 2024-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_propfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirm',
            name='two_percent_rule',
            field=models.BooleanField(default=False),
        ),
    ]
