# Generated by Django 5.1 on 2024-12-22 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_propfirm_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirm',
            name='account_plans',
        ),
        migrations.AddField(
            model_name='propfirm',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='date_published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='payment_options',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cryptocurrency', 'Cryptocurrency'), ('PayPal', 'PayPal'), ('Koka', 'Koka'), ('Skrill', 'Skrill'), ('Neteller', 'Neteller'), ('Google Pay', 'Google Pay'), ('Apple Pay', 'Apple Pay'), ('Payoneer', 'Payoneer'), ('Paysafe Card', 'Paysafe Card'), ('Wise', 'Wise')], max_length=250)),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='payout_options',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Rise', 'Rise'), ('Cryptocurrency', 'Cryptocurrency'), ('Wise', 'Wise')], max_length=250)),
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('one_phase', 'One Phase'), ('two_phase', 'Two Phase'), ('three_phase', 'Three Phase'), ('four_phase', 'Four Phase'), ('instant_funding', 'Instant Funding')], max_length=50)),
                ('account_size', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_split_ratio', models.CharField(max_length=50)),
                ('daily_drawdown', models.CharField(max_length=50)),
                ('total_drawdown', models.CharField(max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('prop_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_plans', to='blog.propfirm')),
            ],
        ),
    ]
