# Generated by Django 5.1 on 2024-12-19 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_propfirm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirm',
            name='about',
        ),
        migrations.AddField(
            model_name='propfirm',
            name='drawdown_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='payout_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='stop_loss_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='payment_options',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cryptocurrency', 'Cryptocurrency'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe')], max_length=250)),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='payout_options',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Cryptocurrency', 'Cryptocurrency'), ('Skrill', 'Skrill'), ('Neteller', 'Neteller')], max_length=250)),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='trading_platforms',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5'), ('CTrader', 'CTrader'), ('MatchTrader', 'MatchTrader'), ('DXTrade', 'DXTrade'), ('In-House Trading Platform', 'In-House Trading Platform')], max_length=250)),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('secret', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
    ]
