# Generated by Django 5.1 on 2024-09-22 19:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_public_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
