# Generated by Django 5.1 on 2024-12-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_propfirm_account_plans_propfirm_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountplan',
            name='account_size',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='year_established',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
