# Generated by Django 5.1 on 2024-10-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_propfirm_phase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirm',
            name='status',
            field=models.CharField(choices=[('DRAFTED', 'Draft'), ('PUBLISHED', 'Publish')], default='DRAFTED', max_length=10),
        ),
    ]
