# Generated by Django 5.1 on 2024-12-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_accountplan_account_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirm',
            name='news_rule',
        ),
        migrations.AddField(
            model_name='accountplan',
            name='leverage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountplan',
            name='minimum_trading_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='expert_advisors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='account_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='trading_platforms',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5'), ('CTrader', 'CTrader'), ('MatchTrader', 'MatchTrader'), ('DXTrade', 'DXTrade'), ('TradeLocker', 'TradeLocker'), ('Trading View', 'Trading View'), ('In-House Trading Platform', 'In-House Trading Platform')], max_length=250)),
        ),
    ]
