# Generated by Django 5.1 on 2024-10-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_propfirm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirm',
            name='status',
        ),
    ]
