# Generated by Django 5.1 on 2024-12-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_propfirm_news_rule_accountplan_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountplan',
            name='profit_target',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='daily_drawdown',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='leverage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='profit_split_ratio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='total_drawdown',
            field=models.CharField(max_length=10),
        ),
    ]
