# Generated by Django 5.1 on 2024-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_accountplan_profit_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propfirm',
            old_name='copy_trading',
            new_name='copy_trading_rule',
        ),
        migrations.RenameField(
            model_name='propfirm',
            old_name='expert_advisors',
            new_name='expert_advisors_rule',
        ),
        migrations.AddField(
            model_name='accountplan',
            name='phase_time_limit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='vpn_and_vps_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='leverage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='profit_split_ratio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='profit_target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='payment_options',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cryptocurrency', 'Cryptocurrency'), ('PayPal', 'PayPal'), ('Koka', 'Koka'), ('Skrill', 'Skrill'), ('Neteller', 'Neteller'), ('Google Pay', 'Google Pay'), ('Apple Pay', 'Apple Pay'), ('Payoneer', 'Payoneer'), ('Paysafe Card', 'Paysafe Card'), ('Wise', 'Wise'), ('Astropay', 'Astropay')], max_length=250)),
        ),
    ]
