# Generated by Django 5.1 on 2024-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_copy_trading_propfirm_copy_trading_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountplan',
            name='daily_drawdown',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='leverage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='minimum_trading_days',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='phase_time_limit',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='profit_split_ratio',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='profit_target',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='total_drawdown',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
