# Generated by Django 5.1 on 2024-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_accountplan_daily_drawdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirm',
            name='expert_advisors_rule',
        ),
        migrations.AddField(
            model_name='propfirm',
            name='weekend_holding_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='payout_options',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Rise', 'Rise'), ('Direct Crypto', 'Direct Crypto'), ('Wise', 'Wise')], max_length=250)),
        ),
    ]
