# Generated by Django 5.1 on 2025-01-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_propfirm_expert_advisors_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountplan',
            name='account_type',
            field=models.CharField(default='Forex', max_length=50),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
