# Generated by Django 5.1 on 2025-01-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_accountplan_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountplan',
            name='phase',
            field=models.CharField(choices=[('one_phase', 'One Phase'), ('two_phase', 'Two Phase'), ('three_phase', 'Three Phase'), ('four_phase', 'Four Phase'), ('instant_funding', 'Instant Funding')], default='Two Phase', max_length=50),
        ),
    ]
