# Generated by Django 5.1 on 2025-01-08 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_accountplan_phase_alter_propfirm_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirm',
            name='broker',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='propfirm',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='account_size',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='phase',
            field=models.CharField(choices=[('one_phase', 'One Phase'), ('two_phase', 'Two Phase'), ('three_phase', 'Three Phase'), ('four_phase', 'Four Phase'), ('instant_funding', 'Instant Funding')], db_index=True, default='two_phase', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='date_published',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='propfirm',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
    ]
