# Generated by Django 5.1 on 2025-01-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_propfirm_broker_propfirm_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirm',
            name='broker',
        ),
    ]
