# Generated by Django 5.1 on 2025-01-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_propfirm_broker_propfirm_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propfirm',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
