# Generated by Django 5.1 on 2025-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_propfirm_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Cloudinary Image URL'),
        ),
    ]
